stages:
  - test

test:
  stage: test
  image: eclipse-temurin:21-jdk
  services:
    - postgres:latest
  variables:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: postgres
  before_script:
    - ./mvnw install:install-file -Dfile=libs/gphoto2-java-1.5-SNAPSHOT.jar
      -DgroupId=org.gphoto -DartifactId=gphoto2-java
      -Dversion=1.5-SNAPSHOT -Dpackaging=jar -B
  script:
    - ./mvnw test -B
  cache:
    key: maven-$CI_COMMIT_REF_SLUG
    paths:
      - ~/.m2/repository
