FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends imagemagick && rm -rf /var/lib/apt/lists/*

COPY fly/target/*-runner /deployments/application

RUN chmod a+x /deployments/*

CMD ./deployments/application                                               \
         -Dquarkus.http.host=0.0.0.0                                        \
         -Dquarkus.datasource.reactive.url=$FREE_DATABASE_URL                    \
         -Dquarkus.hibernate-orm.database.generation=none
