FROM eclipse-temurin:21-jre-jammy

RUN apt-get update && apt-get install -y --no-install-recommends \
    imagemagick ffmpeg postgresql-client \
    && rm -rf /var/lib/apt/lists/*

COPY target/quarkus-app/lib/ /deployments/lib/
COPY target/quarkus-app/*.jar /deployments/
COPY target/quarkus-app/app/ /deployments/app/
COPY target/quarkus-app/quarkus/ /deployments/quarkus/
COPY docker-entrypoint-staging.sh /deployments/entrypoint.sh

RUN chmod +x /deployments/entrypoint.sh

EXPOSE 8080

CMD ["/deployments/entrypoint.sh"]
