# Gradle properties

quarkusPluginId=io.quarkus
quarkusPluginVersion=3.24.5
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.24.5
# org.gradle.jvmargs=-Xmx16g
org.gradle.parallel=false

org.gradle.jvmargs=-Xmx30g -XX:MaxMetaspaceSize=4g
gradle.startParameter.maxParallelForks = 1
