# DevServices konfiguriert JDBC + Reactive URL automatisch (kein Flyway nötig)
quarkus.datasource.jdbc.url=
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.sql-load-script=import-test.sql
resend.mock=true
