# Lokale Docker-DB: docker run -d --rm --name postgres -e POSTGRES_USER=postgres \
#   -e POSTGRES_PASSWORD=postgres -p 5432:5432 postgres:latest
# Start: ./mvnw compile quarkus:dev -Dquarkus.profile=local
quarkus.http.port=8080
quarkus.datasource.reactive.url=postgresql://localhost:5432/postgres?ssl=false&sslmode=disable
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.hibernate-orm.log.sql=false

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000,http://192.168.2.36:3000

jahrbuch.captures.station=false
jahrbuch.captures.path=/home/dboehm/git/git.quarkus/jahrbuch-generator.git/captures/

jahrbuch.fotobox.token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJodHRwczovL2V4YW1wbGUuY29tL2lzc3VlciIsInVwbiI6ImZvdG9ib3gtZ3JvdXAtMzAxIiwiZ3JvdXBzIjpbImZvdG9ib3giXSwiZ3JvdXBfaWQiOjMwMSwidHlwZSI6ImZvdG9ib3giLCJpYXQiOjE3NzY5MDI0MDAsImV4cCI6MTc3ODQ1NzYwMCwianRpIjoiMDkxYWNkODAtYjQzZi00YTFkLTlhODctNWFlYmE4MjEzYjdhIn0.FI8zY5ZFdGFurmIRRF9eiMj8lHTNROU0R2DSUVaQSkJPJFppvJ93PwOd-qmQfQxHyIoM9np66EP7rh_WhvlNxS2M_Bkb8BAAl1hFQ1w_GI6ydxGnKckuFWpK8ELUha83B1Uy6MF5uAXJaIFPVlgNO5mTeCos_4aHBhMf-vJS4eJ4O2dZ9c3mYueXnv0RAFCXXzK14O9NcOvFu7IvTzTJFoS9YJXH7ZCTd7htAnjlG_Fgq4GMpEttyEHaR1jlg9dfpHH7S5FGwc7bcDOmwqIhwEDVb2B_Q9icEAVyU-MMwBQnejVR-03jpVQ7LGknPLGeHNtGbbEOGYptBFPQMNOSYg

resend.mock=false
jahrbuch.app.url=http://localhost:3000
