## quarkus.http.port=8080
%dev.quarkus.http.port=8080
# %dev.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/jamsintown
# %dev.quarkus.datasource.jdbc.url=jdbc:postgresql://fly-user:39bOZlIfQ2YnqizQ3Uos37kN@pgbouncer.vmkq6098vgnr35ln.flympg.net/fly-db
# quarkus.datasource.jdbc.url=jdbc:postgresql://fly-user:39bOZlIfQ2YnqizQ3Uos37kN@pgbouncer.vmkq6098vgnr35ln.flympg.net/fly-db

#%dev.quarkus.datasource.reactive.url=postgresql://pgbouncer.vmkq6098vgnr35ln.flympg.net/fly-db?ssl=false&sslmode=disable
# %dev.quarkus.datasource.reactive.url=postgresql://direct.vmkq6098vgnr35ln.flympg.net/fly-db?ssl=false&sslmode=disable
###### Proxy URL, username and password für managed Postgres bei Fly.io
# %dev.quarkus.datasource.reactive.url=postgresql://localhost:16380/fly-db?ssl=false&sslmode=disable
# %dev.quarkus.datasource.username=fly-user
# %dev.quarkus.datasource.password=39bOZlIfQ2YnqizQ3Uos37kN

###### Proxy URL, username und passwort für free Postgres bei Fly.io
%dev.quarkus.datasource.reactive.url=postgresql://localhost:5433/postgres?ssl=false&sslmode=disable
%dev.quarkus.datasource.username=postgres
%dev.quarkus.datasource.password=yKTSyH4aXUsrB9e

#
#publisher.name=JamsInTown
#
# Pfad für erfasste Bilder
jahrbuch.captures.path=/data/captures/
jahrbuch.captures.station=false
%dev.jahrbuch.captures.station=true

# als ganzzahliges Vielfaches von 1048576 (entspricht 1 MiB)
jahrbuch.upload.max-size=2097152
jahrbuch.upload.allowed-types=.jpg,.jpeg,.png,.gif,.bmp,.webp,.tiff,.tif

# %dev.jahrbuch.captures.path=/home/dboehm/jahrbuch-generator/captures/
%dev.jahrbuch.captures.path=/home/dboehm/git/git.quarkus/jahrbuch-generator.git/captures/

quarkus.datasource.db-kind=postgresql
#quarkus.hibernate-orm.sql-load-script=import.sql
#%dev.quarkus.hibernate-orm.database.generation=drop-and-create
#%dev.quarkus.hibernate-orm.sql-load-script=import-dev.sql
#%test.quarkus.hibernate-orm.sql-load-script=import-dev.sql
%dev.quarkus.hibernate-orm.log.sql=true

%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.origins=http://localhost:3000,https://jahrbuch-generator.fly.dev
# erlaubt ALLE Origins (für Testen)
# %dev.quarkus.http.cors.origins=*
# wenn du nur dein Frontend erlauben willst (empfohlen):
# quarkus.http.cors.origins=https://mein-frontend.fly.dev

smallrye.jwt.sign.key.location=jwt/private-key.pem
mp.jwt.verify.publickey.location=jwt/public-key.pem
mp.jwt.verify.issuer=https://example.com/issuer
quarkus.native.resources.includes=jwt/public-key.pem,jwt/private-key.pem

# Native Image: Initialisierung von AWT/ImageIO zur Laufzeit
# quarkus.native.additional-build-args=--initialize-at-run-time=javax.imageio\,com.sun.imageio,--report-unsupported-elements-at-runtime,-J-Djava.awt.headless=true
# quarkus.native.additional-build-args=--initialize-at-run-time=javax.imageio,--report-unsupported-elements-at-runtime,-J-Djava.awt.headless=true