CREATE SEQUENCE IF NOT EXISTS invitation_sends_seq   START WITH 1    INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS invitation_tokens_seq  START WITH 1    INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS gruppen_seq            START WITH 1    INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS videos_seq             START WITH 1000 INCREMENT BY 50;
CREATE SEQUENCE IF NOT EXISTS reminder_sends_id_seq  START WITH 1    INCREMENT BY 50;
